### PR TITLE
Adding GWN members + MediEvil Wiki rebrand.

### PR DESCRIPTION
**Pull request by RampantSpirit**
Let me know if there are any issues.

### CODE REVIEW

**Comment by invalidCards** [comment]
@RampantSpirit The key for the MediEvil Wiki/Gallowpedia should not be changed, this is what the database uses to keep track of user preferences. Please revert the change to the key and add the new key as an alias instead.

**Comment by RampantSpirit** [comment]
Alright, all done. :)

**Comment by RampantSpirit** [comment]
@invalidCards Should be all good now I think, but let me know if not.

**Comment by invalidCards** [comment]
Wow I completely forgot about this, sorry for that! I'll merge it now and it should be added to the bot within the next 15 minutes or so.

**Pull request merged**
